#!/bin/bash
# Bradford Smith
# ~/.config/bspwm/bspwmrc
# updated: 2019-09-02

bspc config click_to_focus true
bspc config focused_border_color \#87ff87
#bspc config active_border_color \#87ff87

bspc rule -a Pinentry state=floating

btops&
~/.config/polybar/launch.sh
dunst&
nm-applet&
xautolock -time 5 -locker 'i3lock-fancy -p'&
