#!/bin/bash
# Bradford Smith
# 02/08/2017
# Git hook to run after `git pull`

git_root="$(git rev-parse --show-toplevel)"
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_file() {
    echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# if the gitconfig file has been updated, run the hasGitPushSimple.sh script
check_file gitconfig "$git_root/bin/hasGitPushSimple.sh"

# Force git to refresh the index regarding the gitconfig file.  This bit is
# necessary because even though the changes are hidden by a filter git thinks
# the file changed, but `git diff` will show no changes.
git update-index --really-refresh -q gitconfig
